volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
  kestra:
    image: kestra/kestra:latest-full
    env_file:
      - .env_encoded
    pull_policy: always
    # Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.
    user: "root"
    command: server standalone --worker-thread=128
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      SECRET_SERVICE_ACCOUNT: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY29tcGVsbGlu
Zy1wYWN0LTMyNjUyMSIsCiAgInByaXZhdGVfa2V5X2lkIjogIjhiN2RlNjE4ZDE4NDY2NWViZjgw
M2Y5OGU4NDhmOTgwOGUxNmQzMzYiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZB
VEUgS0VZLS0tLS1cbk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VB
QW9JQkFRQ29TODNaWVVGM3hxczFcbjQrb2FYTUNDWEZZTzhLRnRoa2NXUnJUeU52eXlrMTB4cVll
WHRSUGxGeVV3SnF6UDVIYklHd012V1huSC9TQ2lcbkt0VTJ6bHQrTmN6ZHFkcHBHaWNORWtra3Z6
RFFVL0RsQStIblVzczFGWUNSVmJWNDg5N2dwNmFreStwcm04bHdcbjdUY3RKTnFWOGp1czZncjMx
TTBaL0pvd2JkeHJpZ3lhbzkyQk5aZHVJeS8yZ0VjSUFuaUJHajdlVjk4MXdweGdcbjBPS0VsTnFx
WHN6bS9kTHpPUlZycy9KdTFtSStjY2RGTWtqL2N3UHRvM0kxcVJqa2o5dW9DNE0zK0NQL0RWSjlc
bjRuV0IrRmx2eENJU1duNWhXeEdYa3FFNkpGOHk5dUJsUWRabEp6U3BjS1dRRXN2WUJEN0VoeXBo
bFEwWitKM0FcbnN2VlNKSjBqQWdNQkFBRUNnZ0VBTGpTSnNwbmlDSWx4N2h6QjVEVDg0WTJLVHhX
L3JEdEdmeFl3amFPTkkxWVVcbkt4TlpWOHh1UnVKZzRtUnI0N1BjN0xtRjJWVWVlMHJDeitNa29L
UnRPQ3g3TDR4M200MkRsVElsQk1LOUd5VkFcbnFRKzAwUGJKTmF6T25KaEVkNDIwN2tiNUdKdW5v
NTJrNDYwdERlYmxZRytkOUs1WkRvdk5OOHBEWnZKeXBzOVFcbjdWR1ZZSmJreS9NZjdtQlltVGN3
ekROTzNZWSt5aWlham1lR3JJUGR3TExvMVZUQkRKYU1jdHMrQlk2TFdscHVcbjlTQitXODZXdmFX
T2pyUFF4bXVxOTYxeGgvQ3YwK1EvcEdZaktqditoa3hKV1pOUmFuZDNvU0dJTjk3anZTdlBcbkYr
MEFPdmJTTDNxbzMvNm02eXlFbGdQMmtNT2IzbWxoWVRwWmFhWE00UUtCZ1FEWWNMOGdSRFVuVEtS
Y2lENXNcbjlkbUg0N2pSSnNCamNORkw3RzE2ZkJRbG15eU1OVXhVVDBFYVhuNk0vTHExOTIzRm9E
RlgzamVPT01odG9SV21cbldLYUFpdFFqRk5TSEtpL0FOLytaajM0a0FnemJxOUtjN0E5SVZSSGg4
NmNEUHJJbEFzNElsNG5raERqR0FiRWVcblBhUXpxc20zT2pzOGZZTndsSG9rbEZJRmNRS0JnUURI
RG1KTnNMS3RocHo1Nk40NnZaUXo2QStCRldFb1RiVmNcbjBZV2pJbjA3WElBZ3ZETUV6YWxtZHlO
OE9pdTFlL1hOZmVuaTA1N2dKQlY2RWNvRXNNL2grVjdwV0NKb0ZMdWFcbkpWMWFKRjh4a1pZMjl5
SFc0RFIrZExsL0tNdDVvZVZ1UW5zek83eVJ2c3Q3THkwWDlUM2JnKzJkNGkvdkFGamxcbkI0U25p
YmV4MHdLQmdBOUtkOVk1dTErWlpJczgvTndKeW1KMVRodElsNUx1NTNwcnE1aFpwN3E0YWI5R0RL
eHdcbkpQTk45YmJVTEFTckJGQlA3dXg4UUlTRnNuTThUQ0ZDWmhEeXZlWDBsTWN2emN2UXFQZ2FV
UmtPSkFabzd5b3lcbjZ5bDdDUlpqZGtzZVpNdUVsVFc2THYyNzhaN2JnNzNWTVFLTmNFN0hpR1BQ
b2plVDVjVXJ6VmVoQW9HQUVnQ01cbkJXaXdrQjczZldhQkNxRHdrVTB3Y2NVa04wZm4yaEFjM09j
V21sTEFSN1dkaTVhcDlsbFovVGNwa3MwMktySnpcbmY0OFI5RVZ2Sjg0S0RpaUxkRzFnRnd4Z2VE
Yy96QzRLNWtjWjBOclEwZ0hCcnJReUt5bVZTUm5BWlN5dUdpMnJcbkJMUW5WcXNCcmc5VExiS0JP
S1FTemsrUmREVDgxU0c3N29iMjlQOENnWUJ6ZG1ER214UkJtVklCRTl5bXZ6dG9cbnFRVzl4eE9M
bEF0SGQyZ2VqU0NPZHhCVkVDRFY1VWdoUGlJZ2xjbUpXRDBrbXY1c0JiRDRYcDdQb3h1aGk5Y2Jc
bnFiM1RSMTU3dkUwUndnODlMRFBMNmt5dHFQKzNlelFvQmdBOWJnb0J3eW03RjhFZGZIVktqRmRt
MTNKaHZrUGZcbmpYWWQ4YmFrRVVseDhMUHhXd1lPeVE9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVkt
LS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogInRpbmEtOTc4QGNvbXBlbGxpbmctcGFjdC0zMjY1
MjEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAxMDMxNzUwODgx
MDkyNTkwODI2IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28v
b2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5j
b20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cu
Z29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwi
OiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS90aW5h
LTk3OCU0MGNvbXBlbGxpbmctcGFjdC0zMjY1MjEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAog
ICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
